#!/bin/bash
set -e

if [ -z "$LLVM_ROOT" ]; then
  echo "LLVM_ROOT not set in env" >&2
  exit 1
fi

D=$PWD; cd "$LLVM_ROOT"; LLVM_ROOT=$PWD; cd "$D"
D=$PWD; cd "$(dirname "$0")"; LLVMBOX_UTILS=$PWD; cd "$D"

case "$0" in
  *c++)
    CLANG=$LLVM_ROOT/bin/clang++
    ARGS=( $("$LLVMBOX_UTILS"/config --cxxflags --ldflags-cxx) )
    ;;
  *)
    CLANG=$LLVM_ROOT/bin/clang
    ARGS=( $("$LLVMBOX_UTILS"/config --cflags --ldflags) )
    ;;
esac

# since we are passing LDFLAGS unconditionally...
ARGS+=( -Wno-unused-command-line-argument )

if [ "$1" = "--print-cmd" ]; then
  shift
  echo "$CLANG" "${ARGS[@]}" "$@"
  exit
fi
exec "$CLANG" "${ARGS[@]}" "$@"
